/// Druid 支持的数据库类型。
///
/// 对应 Java：`com.alibaba.druid.DbType`。Rust variant 使用 PascalCase，
/// [`Self::as_str`] 保留 Java enum 的精确外部名称。
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DbType {
    Other,
    Jtds,
    Hsql,
    Db2,
    PostgreSql,
    SqlServer,
    Oracle,
    MySql,
    MariaDb,
    Derby,
    Hive,
    H2,
    Dm,
    Kingbase,
    Gbase,
    OceanBase,
    Informix,
    Odps,
    Teradata,
    Phoenix,
    Edb,
    Kylin,
    SQLite,
    Ads,
    Presto,
    ElasticSearch,
    Hbase,
    Drds,
    ClickHouse,
    Blink,
    Spark,
    OceanBaseOracle,
    PolarDb,
    AliOracle,
    Mock,
    Sybase,
    HighGo,
    Greenplum,
    GaussDb,
    Trino,
    Oscar,
    TiDb,
    TyDb,
    StarRocks,
    GoldenDb,
    Snowflake,
    Redshift,
    Hologres,
    BigQuery,
    Impala,
    Doris,
    Lealone,
    Athena,
    PolarDbX,
    SuperSql,
    Databricks,
    AdbMySql,
    PolarDb2,
    Synapse,
    Ingres,
    Cloudscape,
    TimesTen,
    As400,
    SapDb,
    Kdb,
    Log4Jdbc,
    Xugu,
    FirebirdSql,
    JsqlConnect,
    JTurbo,
    Interbase,
    Pointbase,
    Edbc,
    Mimer,
    TaosData,
    SunDb,
}

impl DbType {
    /// 按 Java enum 名称和两个兼容别名解析。
    #[must_use]
    pub fn of(name: &str) -> Option<Self> {
        let normalized = name.trim().to_ascii_lowercase().replace('-', "_");
        Some(match normalized.as_str() {
            "other" => Self::Other,
            "jtds" => Self::Jtds,
            "hsql" | "hsqldb" => Self::Hsql,
            "db2" => Self::Db2,
            "postgresql" | "postgres" | "pg" => Self::PostgreSql,
            "sqlserver" | "mssql" => Self::SqlServer,
            "oracle" => Self::Oracle,
            "mysql" => Self::MySql,
            "mariadb" => Self::MariaDb,
            "derby" => Self::Derby,
            "hive" => Self::Hive,
            "h2" => Self::H2,
            "dm" => Self::Dm,
            "kingbase" | "kingbase8" => Self::Kingbase,
            "gbase" => Self::Gbase,
            "oceanbase" => Self::OceanBase,
            "informix" => Self::Informix,
            "odps" | "maxcompute" => Self::Odps,
            "teradata" => Self::Teradata,
            "phoenix" => Self::Phoenix,
            "edb" => Self::Edb,
            "kylin" => Self::Kylin,
            "sqlite" => Self::SQLite,
            "ads" | "aliyun_ads" => Self::Ads,
            "presto" => Self::Presto,
            "elastic_search" | "elasticsearch" => Self::ElasticSearch,
            "hbase" => Self::Hbase,
            "drds" => Self::Drds,
            "clickhouse" => Self::ClickHouse,
            "blink" => Self::Blink,
            "spark" | "antspark" => Self::Spark,
            "oceanbase_oracle" => Self::OceanBaseOracle,
            "polardb" => Self::PolarDb,
            "ali_oracle" => Self::AliOracle,
            "mock" => Self::Mock,
            "sybase" => Self::Sybase,
            "highgo" => Self::HighGo,
            "greenplum" => Self::Greenplum,
            "gaussdb" | "opengauss" => Self::GaussDb,
            "trino" => Self::Trino,
            "oscar" => Self::Oscar,
            "tidb" => Self::TiDb,
            "tydb" => Self::TyDb,
            "starrocks" => Self::StarRocks,
            "goldendb" => Self::GoldenDb,
            "snowflake" => Self::Snowflake,
            "redshift" => Self::Redshift,
            "hologres" => Self::Hologres,
            "bigquery" => Self::BigQuery,
            "impala" => Self::Impala,
            "doris" => Self::Doris,
            "lealone" => Self::Lealone,
            "athena" => Self::Athena,
            "polardbx" => Self::PolarDbX,
            "supersql" => Self::SuperSql,
            "databricks" => Self::Databricks,
            "adb_mysql" => Self::AdbMySql,
            "polardb2" => Self::PolarDb2,
            "synapse" => Self::Synapse,
            "ingres" => Self::Ingres,
            "cloudscape" => Self::Cloudscape,
            "timesten" => Self::TimesTen,
            "as400" => Self::As400,
            "sapdb" => Self::SapDb,
            "kdb" => Self::Kdb,
            "log4jdbc" => Self::Log4Jdbc,
            "xugu" => Self::Xugu,
            "firebirdsql" => Self::FirebirdSql,
            "jsqlconnect" => Self::JsqlConnect,
            "jturbo" => Self::JTurbo,
            "interbase" => Self::Interbase,
            "pointbase" => Self::Pointbase,
            "edbc" => Self::Edbc,
            "mimer" => Self::Mimer,
            "taosdata" => Self::TaosData,
            "sundb" => Self::SunDb,
            _ => return None,
        })
    }

    /// 返回 Java enum 的精确名称。
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Other => "other",
            Self::Jtds => "jtds",
            Self::Hsql => "hsql",
            Self::Db2 => "db2",
            Self::PostgreSql => "postgresql",
            Self::SqlServer => "sqlserver",
            Self::Oracle => "oracle",
            Self::MySql => "mysql",
            Self::MariaDb => "mariadb",
            Self::Derby => "derby",
            Self::Hive => "hive",
            Self::H2 => "h2",
            Self::Dm => "dm",
            Self::Kingbase => "kingbase",
            Self::Gbase => "gbase",
            Self::OceanBase => "oceanbase",
            Self::Informix => "informix",
            Self::Odps => "odps",
            Self::Teradata => "teradata",
            Self::Phoenix => "phoenix",
            Self::Edb => "edb",
            Self::Kylin => "kylin",
            Self::SQLite => "sqlite",
            Self::Ads => "ads",
            Self::Presto => "presto",
            Self::ElasticSearch => "elastic_search",
            Self::Hbase => "hbase",
            Self::Drds => "drds",
            Self::ClickHouse => "clickhouse",
            Self::Blink => "blink",
            Self::Spark => "spark",
            Self::OceanBaseOracle => "oceanbase_oracle",
            Self::PolarDb => "polardb",
            Self::AliOracle => "ali_oracle",
            Self::Mock => "mock",
            Self::Sybase => "sybase",
            Self::HighGo => "highgo",
            Self::Greenplum => "greenplum",
            Self::GaussDb => "gaussdb",
            Self::Trino => "trino",
            Self::Oscar => "oscar",
            Self::TiDb => "tidb",
            Self::TyDb => "tydb",
            Self::StarRocks => "starrocks",
            Self::GoldenDb => "goldendb",
            Self::Snowflake => "snowflake",
            Self::Redshift => "redshift",
            Self::Hologres => "hologres",
            Self::BigQuery => "bigquery",
            Self::Impala => "impala",
            Self::Doris => "doris",
            Self::Lealone => "lealone",
            Self::Athena => "athena",
            Self::PolarDbX => "polardbx",
            Self::SuperSql => "supersql",
            Self::Databricks => "databricks",
            Self::AdbMySql => "adb_mysql",
            Self::PolarDb2 => "polardb2",
            Self::Synapse => "synapse",
            Self::Ingres => "ingres",
            Self::Cloudscape => "cloudscape",
            Self::TimesTen => "timesten",
            Self::As400 => "as400",
            Self::SapDb => "sapdb",
            Self::Kdb => "kdb",
            Self::Log4Jdbc => "log4jdbc",
            Self::Xugu => "xugu",
            Self::FirebirdSql => "firebirdsql",
            Self::JsqlConnect => "JSQLConnect",
            Self::JTurbo => "JTurbo",
            Self::Interbase => "interbase",
            Self::Pointbase => "pointbase",
            Self::Edbc => "edbc",
            Self::Mimer => "mimer",
            Self::TaosData => "taosdata",
            Self::SunDb => "sundb",
        }
    }

    /// 返回 Java `mask`。
    #[must_use]
    pub const fn mask(self) -> u64 {
        let bit = match self {
            Self::Other => Some(0),
            Self::Jtds => Some(1),
            Self::Hsql => Some(2),
            Self::Db2 => Some(3),
            Self::PostgreSql => Some(4),
            Self::SqlServer => Some(5),
            Self::Oracle => Some(6),
            Self::MySql => Some(7),
            Self::MariaDb => Some(8),
            Self::Derby => Some(9),
            Self::Hive => Some(10),
            Self::H2 => Some(11),
            Self::Dm => Some(12),
            Self::Kingbase => Some(13),
            Self::Gbase => Some(14),
            Self::OceanBase => Some(15),
            Self::Informix => Some(16),
            Self::Odps => Some(17),
            Self::Teradata => Some(18),
            Self::Phoenix => Some(19),
            Self::Edb => Some(20),
            Self::Kylin => Some(21),
            Self::SQLite => Some(22),
            Self::Ads => Some(23),
            Self::Presto => Some(24),
            Self::ElasticSearch => Some(25),
            Self::Hbase => Some(26),
            Self::Drds => Some(27),
            Self::ClickHouse => Some(28),
            Self::Blink => Some(29),
            Self::Spark => Some(30),
            Self::OceanBaseOracle => Some(31),
            Self::PolarDb => Some(32),
            Self::AliOracle => Some(33),
            Self::Mock => Some(34),
            Self::Sybase => Some(35),
            Self::HighGo => Some(36),
            Self::Greenplum => Some(37),
            Self::GaussDb => Some(38),
            Self::Trino => Some(39),
            Self::Oscar => Some(40),
            Self::TiDb => Some(41),
            Self::TyDb => Some(42),
            Self::StarRocks => Some(43),
            Self::GoldenDb => Some(44),
            Self::Snowflake => Some(45),
            Self::Redshift => Some(46),
            Self::Hologres => Some(47),
            Self::BigQuery => Some(48),
            Self::Impala => Some(49),
            Self::Doris => Some(50),
            Self::Lealone => Some(51),
            Self::Athena => Some(52),
            Self::PolarDbX => Some(53),
            Self::SuperSql => Some(54),
            Self::Databricks => Some(55),
            Self::AdbMySql => Some(56),
            Self::PolarDb2 => Some(57),
            Self::Synapse => Some(58),
            _ => None,
        };
        match bit {
            Some(bit) => 1_u64 << bit,
            None => 0,
        }
    }

    /// 返回是否属于 PostgreSQL 风格。
    #[must_use]
    pub const fn is_postgresql_style(self) -> bool {
        matches!(
            self,
            Self::PostgreSql | Self::Edb | Self::Greenplum | Self::Hologres
        )
    }
}

impl std::fmt::Display for DbType {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_str())
    }
}
