use super::rdbc_sql_type::SqlType;

/// RDBC enum of standard SQL types defined by the Java 8 contract.
///
/// Adapted from Java: `java.sql.JDBCType`. Every variant implements `SqlType`; names are the
/// standard constants, vendor is `java.sql`, and numbers match `Types`. `RefCursor` and the
/// timezone-aware temporal types are RDBC 4.2 additions.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RdbcType {
    Bit,
    TinyInt,
    SmallInt,
    Integer,
    BigInt,
    Float,
    Real,
    Double,
    Numeric,
    Decimal,
    Char,
    VarChar,
    LongVarChar,
    Date,
    Time,
    Timestamp,
    Binary,
    VarBinary,
    LongVarBinary,
    Null,
    Other,
    JavaObject,
    Distinct,
    Struct,
    Array,
    Blob,
    Clob,
    Ref,
    DataLink,
    Boolean,
    RowId,
    NChar,
    NVarChar,
    LongNVarChar,
    NClob,
    SqlXml,
    RefCursor,
    TimeWithTimezone,
    TimestampWithTimezone,
}

impl SqlType for RdbcType {
    fn name(&self) -> &'static str {
        match self {
            Self::Bit => "BIT",
            Self::TinyInt => "TINYINT",
            Self::SmallInt => "SMALLINT",
            Self::Integer => "INTEGER",
            Self::BigInt => "BIGINT",
            Self::Float => "FLOAT",
            Self::Real => "REAL",
            Self::Double => "DOUBLE",
            Self::Numeric => "NUMERIC",
            Self::Decimal => "DECIMAL",
            Self::Char => "CHAR",
            Self::VarChar => "VARCHAR",
            Self::LongVarChar => "LONGVARCHAR",
            Self::Date => "DATE",
            Self::Time => "TIME",
            Self::Timestamp => "TIMESTAMP",
            Self::Binary => "BINARY",
            Self::VarBinary => "VARBINARY",
            Self::LongVarBinary => "LONGVARBINARY",
            Self::Null => "NULL",
            Self::Other => "OTHER",
            Self::JavaObject => "JAVA_OBJECT",
            Self::Distinct => "DISTINCT",
            Self::Struct => "STRUCT",
            Self::Array => "ARRAY",
            Self::Blob => "BLOB",
            Self::Clob => "CLOB",
            Self::Ref => "REF",
            Self::DataLink => "DATALINK",
            Self::Boolean => "BOOLEAN",
            Self::RowId => "ROWID",
            Self::NChar => "NCHAR",
            Self::NVarChar => "NVARCHAR",
            Self::LongNVarChar => "LONGNVARCHAR",
            Self::NClob => "NCLOB",
            Self::SqlXml => "SQLXML",
            Self::RefCursor => "REF_CURSOR",
            Self::TimeWithTimezone => "TIME_WITH_TIMEZONE",
            Self::TimestampWithTimezone => "TIMESTAMP_WITH_TIMEZONE",
        }
    }

    fn vendor(&self) -> &'static str {
        "java.sql"
    }

    fn vendor_type_number(&self) -> i32 {
        match self {
            Self::Bit => -7,
            Self::TinyInt => -6,
            Self::SmallInt => 5,
            Self::Integer => 4,
            Self::BigInt => -5,
            Self::Float => 6,
            Self::Real => 7,
            Self::Double => 8,
            Self::Numeric => 2,
            Self::Decimal => 3,
            Self::Char => 1,
            Self::VarChar => 12,
            Self::LongVarChar => -1,
            Self::Date => 91,
            Self::Time => 92,
            Self::Timestamp => 93,
            Self::Binary => -2,
            Self::VarBinary => -3,
            Self::LongVarBinary => -4,
            Self::Null => 0,
            Self::Other => 1111,
            Self::JavaObject => 2000,
            Self::Distinct => 2001,
            Self::Struct => 2002,
            Self::Array => 2003,
            Self::Blob => 2004,
            Self::Clob => 2005,
            Self::Ref => 2006,
            Self::DataLink => 70,
            Self::Boolean => 16,
            Self::RowId => -8,
            Self::NChar => -15,
            Self::NVarChar => -9,
            Self::LongNVarChar => -16,
            Self::NClob => 2011,
            Self::SqlXml => 2009,
            Self::RefCursor => 2012,
            Self::TimeWithTimezone => 2013,
            Self::TimestampWithTimezone => 2014,
        }
    }
}
