//! Druid SQL lexer token。

macro_rules! define_tokens {
    ($($variant:ident => ($java_name:literal, $name:expr)),+ $(,)?) => {
        /// Druid SQL lexer 的完整 Token 返回域。
        ///
        /// 对应 Java：`com.alibaba.druid.sql.parser.Token`。该枚举独立于
        /// `sqlparser::tokenizer::Token`，保留 Druid 的关键字、literal、
        /// comment、方言词与操作符分类，以及部分 token 的 nullable `name` 字段。
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[repr(u16)]
        pub enum Token {
            $(
                #[doc = concat!("对应 Java `Token.", $java_name, "`。")]
                $variant,
            )+
        }

        impl Token {
            /// Java 声明顺序中的全部 335 项 Token。
            pub const ALL: &'static [Self] = &[$(Self::$variant),+];

            /// 返回 Java `Enum#name()`。
            #[must_use]
            pub const fn java_name(self) -> &'static str {
                match self {
                    $(Self::$variant => $java_name,)+
                }
            }

            /// 返回 Java Token 的 public `name` 字段。
            ///
            /// EOF、ERROR、IDENTIFIER、literal/comment 等使用无参构造器，
            /// 对应 Java null。
            #[must_use]
            pub const fn name(self) -> Option<&'static str> {
                match self {
                    $(Self::$variant => $name,)+
                }
            }

            /// 返回 Java `Enum#ordinal()`。
            #[must_use]
            pub const fn ordinal(self) -> u16 {
                self as u16
            }

            /// 按 Java 枚举常量名称严格解析。
            #[must_use]
            pub fn value_of(name: &str) -> Option<Self> {
                Self::ALL
                    .iter()
                    .copied()
                    .find(|token| token.java_name() == name)
            }
        }
    };
}

define_tokens! {
    Select => ("SELECT", Some("SELECT")),
    Delete => ("DELETE", Some("DELETE")),
    Insert => ("INSERT", Some("INSERT")),
    Update => ("UPDATE", Some("UPDATE")),
    From => ("FROM", Some("FROM")),
    Having => ("HAVING", Some("HAVING")),
    Where => ("WHERE", Some("WHERE")),
    Order => ("ORDER", Some("ORDER")),
    By => ("BY", Some("BY")),
    Group => ("GROUP", Some("GROUP")),
    Into => ("INTO", Some("INTO")),
    As => ("AS", Some("AS")),
    Create => ("CREATE", Some("CREATE")),
    Alter => ("ALTER", Some("ALTER")),
    Drop => ("DROP", Some("DROP")),
    Set => ("SET", Some("SET")),
    Null => ("NULL", Some("NULL")),
    Not => ("NOT", Some("NOT")),
    Distinct => ("DISTINCT", Some("DISTINCT")),
    Distinctrow => ("DISTINCTROW", Some("DISTINCTROW")),
    Table => ("TABLE", Some("TABLE")),
    Tablespace => ("TABLESPACE", Some("TABLESPACE")),
    View => ("VIEW", Some("VIEW")),
    Sequence => ("SEQUENCE", Some("SEQUENCE")),
    Trigger => ("TRIGGER", Some("TRIGGER")),
    User => ("USER", Some("USER")),
    Index => ("INDEX", Some("INDEX")),
    Session => ("SESSION", Some("SESSION")),
    Procedure => ("PROCEDURE", Some("PROCEDURE")),
    Function => ("FUNCTION", Some("FUNCTION")),
    Primary => ("PRIMARY", Some("PRIMARY")),
    Key => ("KEY", Some("KEY")),
    Default => ("DEFAULT", Some("DEFAULT")),
    Constraint => ("CONSTRAINT", Some("CONSTRAINT")),
    Check => ("CHECK", Some("CHECK")),
    Unique => ("UNIQUE", Some("UNIQUE")),
    Foreign => ("FOREIGN", Some("FOREIGN")),
    References => ("REFERENCES", Some("REFERENCES")),
    Language => ("LANGUAGE", Some("LANGUAGE")),
    Partial => ("PARTIAL", Some("PARTIAL")),
    Explain => ("EXPLAIN", Some("EXPLAIN")),
    For => ("FOR", Some("FOR")),
    Reverse => ("REVERSE", Some("REVERSE")),
    If => ("IF", Some("IF")),
    Local => ("LOCAL", Some("LOCAL")),
    Global => ("GLOBAL", Some("GLOBAL")),
    All => ("ALL", Some("ALL")),
    Union => ("UNION", Some("UNION")),
    Except => ("EXCEPT", Some("EXCEPT")),
    Intersect => ("INTERSECT", Some("INTERSECT")),
    Minus => ("MINUS", Some("MINUS")),
    Inner => ("INNER", Some("INNER")),
    Left => ("LEFT", Some("LEFT")),
    Right => ("RIGHT", Some("RIGHT")),
    Full => ("FULL", Some("FULL")),
    Outer => ("OUTER", Some("OUTER")),
    Join => ("JOIN", Some("JOIN")),
    StraightJoin => ("STRAIGHT_JOIN", Some("STRAIGHT_JOIN")),
    On => ("ON", Some("ON")),
    Schema => ("SCHEMA", Some("SCHEMA")),
    Cast => ("CAST", Some("CAST")),
    Column => ("COLUMN", Some("COLUMN")),
    Use => ("USE", Some("USE")),
    Database => ("DATABASE", Some("DATABASE")),
    To => ("TO", Some("TO")),
    And => ("AND", Some("AND")),
    Or => ("OR", Some("OR")),
    Xor => ("XOR", Some("XOR")),
    Case => ("CASE", Some("CASE")),
    When => ("WHEN", Some("WHEN")),
    Then => ("THEN", Some("THEN")),
    Else => ("ELSE", Some("ELSE")),
    Elsif => ("ELSIF", Some("ELSIF")),
    Elseif => ("ELSEIF", Some("ELSEIF")),
    End => ("END", Some("END")),
    Exists => ("EXISTS", Some("EXISTS")),
    In => ("IN", Some("IN")),
    New => ("NEW", Some("NEW")),
    Asc => ("ASC", Some("ASC")),
    Desc => ("DESC", Some("DESC")),
    Is => ("IS", Some("IS")),
    Like => ("LIKE", Some("LIKE")),
    Escape => ("ESCAPE", Some("ESCAPE")),
    Between => ("BETWEEN", Some("BETWEEN")),
    Values => ("VALUES", Some("VALUES")),
    Interval => ("INTERVAL", Some("INTERVAL")),
    Lock => ("LOCK", Some("LOCK")),
    Some => ("SOME", Some("SOME")),
    Any => ("ANY", Some("ANY")),
    Truncate => ("TRUNCATE", Some("TRUNCATE")),
    Return => ("RETURN", Some("RETURN")),
    True => ("TRUE", Some("TRUE")),
    False => ("FALSE", Some("FALSE")),
    Limit => ("LIMIT", Some("LIMIT")),
    Kill => ("KILL", Some("KILL")),
    Identified => ("IDENTIFIED", Some("IDENTIFIED")),
    Password => ("PASSWORD", Some("PASSWORD")),
    Dual => ("DUAL", Some("DUAL")),
    Binary => ("BINARY", Some("BINARY")),
    Show => ("SHOW", Some("SHOW")),
    Replace => ("REPLACE", Some("REPLACE")),
    Period => ("PERIOD", Some("PERIOD")),
    Bits => ("BITS", Some("BITS")),
    While => ("WHILE", Some("WHILE")),
    Do => ("DO", Some("DO")),
    Leave => ("LEAVE", Some("LEAVE")),
    Iterate => ("ITERATE", Some("ITERATE")),
    Repeat => ("REPEAT", Some("REPEAT")),
    Until => ("UNTIL", Some("UNTIL")),
    Open => ("OPEN", Some("OPEN")),
    Close => ("CLOSE", Some("CLOSE")),
    Out => ("OUT", Some("OUT")),
    Inout => ("INOUT", Some("INOUT")),
    Exit => ("EXIT", Some("EXIT")),
    Undo => ("UNDO", Some("UNDO")),
    Sqlstate => ("SQLSTATE", Some("SQLSTATE")),
    Condition => ("CONDITION", Some("CONDITION")),
    Div => ("DIV", Some("DIV")),
    Get => ("GET", Some("GET")),
    Diagnostics => ("DIAGNOSTICS", Some("DIAGNOSTICS")),
    Window => ("WINDOW", Some("WINDOW")),
    Offset => ("OFFSET", Some("OFFSET")),
    Row => ("ROW", Some("ROW")),
    Rows => ("ROWS", Some("ROWS")),
    Only => ("ONLY", Some("ONLY")),
    First => ("FIRST", Some("FIRST")),
    Next => ("NEXT", Some("NEXT")),
    Fetch => ("FETCH", Some("FETCH")),
    Of => ("OF", Some("OF")),
    Share => ("SHARE", Some("SHARE")),
    Nowait => ("NOWAIT", Some("NOWAIT")),
    Recursive => ("RECURSIVE", Some("RECURSIVE")),
    Temporary => ("TEMPORARY", Some("TEMPORARY")),
    Temp => ("TEMP", Some("TEMP")),
    Unlogged => ("UNLOGGED", Some("UNLOGGED")),
    Restart => ("RESTART", Some("RESTART")),
    Identity => ("IDENTITY", Some("IDENTITY")),
    Continue => ("CONTINUE", Some("CONTINUE")),
    Cascade => ("CASCADE", Some("CASCADE")),
    Restrict => ("RESTRICT", Some("RESTRICT")),
    Using => ("USING", Some("USING")),
    Current => ("CURRENT", Some("CURRENT")),
    Returning => ("RETURNING", Some("RETURNING")),
    Comment => ("COMMENT", Some("COMMENT")),
    Over => ("OVER", Some("OVER")),
    Type => ("TYPE", Some("TYPE")),
    Ilike => ("ILIKE", Some("ILIKE")),
    Rlike => ("RLIKE", Some("RLIKE")),
    Fulltext => ("FULLTEXT", Some("FULLTEXT")),
    Start => ("START", Some("START")),
    Prior => ("PRIOR", Some("PRIOR")),
    Connect => ("CONNECT", Some("CONNECT")),
    With => ("WITH", Some("WITH")),
    Extract => ("EXTRACT", Some("EXTRACT")),
    Cursor => ("CURSOR", Some("CURSOR")),
    Merge => ("MERGE", Some("MERGE")),
    Matched => ("MATCHED", Some("MATCHED")),
    Errors => ("ERRORS", Some("ERRORS")),
    Reject => ("REJECT", Some("REJECT")),
    Unlimited => ("UNLIMITED", Some("UNLIMITED")),
    Begin => ("BEGIN", Some("BEGIN")),
    Exclusive => ("EXCLUSIVE", Some("EXCLUSIVE")),
    Mode => ("MODE", Some("MODE")),
    Wait => ("WAIT", Some("WAIT")),
    Advise => ("ADVISE", Some("ADVISE")),
    Sysdate => ("SYSDATE", Some("SYSDATE")),
    Declare => ("DECLARE", Some("DECLARE")),
    Exception => ("EXCEPTION", Some("EXCEPTION")),
    Grant => ("GRANT", Some("GRANT")),
    Revoke => ("REVOKE", Some("REVOKE")),
    Loop => ("LOOP", Some("LOOP")),
    Goto => ("GOTO", Some("GOTO")),
    Commit => ("COMMIT", Some("COMMIT")),
    Savepoint => ("SAVEPOINT", Some("SAVEPOINT")),
    Cross => ("CROSS", Some("CROSS")),
    Pctfree => ("PCTFREE", Some("PCTFREE")),
    Initrans => ("INITRANS", Some("INITRANS")),
    Maxtrans => ("MAXTRANS", Some("MAXTRANS")),
    Initially => ("INITIALLY", Some("INITIALLY")),
    Enable => ("ENABLE", Some("ENABLE")),
    Disable => ("DISABLE", Some("DISABLE")),
    Segment => ("SEGMENT", Some("SEGMENT")),
    Creation => ("CREATION", Some("CREATION")),
    Immediate => ("IMMEDIATE", Some("IMMEDIATE")),
    Deferred => ("DEFERRED", Some("DEFERRED")),
    Storage => ("STORAGE", Some("STORAGE")),
    Minextents => ("MINEXTENTS", Some("MINEXTENTS")),
    Maxextents => ("MAXEXTENTS", Some("MAXEXTENTS")),
    Maxsize => ("MAXSIZE", Some("MAXSIZE")),
    Pctincrease => ("PCTINCREASE", Some("PCTINCREASE")),
    FlashCache => ("FLASH_CACHE", Some("FLASH_CACHE")),
    CellFlashCache => ("CELL_FLASH_CACHE", Some("CELL_FLASH_CACHE")),
    None => ("NONE", Some("NONE")),
    Lob => ("LOB", Some("LOB")),
    Store => ("STORE", Some("STORE")),
    Chunk => ("CHUNK", Some("CHUNK")),
    Cache => ("CACHE", Some("CACHE")),
    Nocache => ("NOCACHE", Some("NOCACHE")),
    Logging => ("LOGGING", Some("LOGGING")),
    Nocompress => ("NOCOMPRESS", Some("NOCOMPRESS")),
    KeepDuplicates => ("KEEP_DUPLICATES", Some("KEEP_DUPLICATES")),
    Exceptions => ("EXCEPTIONS", Some("EXCEPTIONS")),
    Purge => ("PURGE", Some("PURGE")),
    Compute => ("COMPUTE", Some("COMPUTE")),
    Analyze => ("ANALYZE", Some("ANALYZE")),
    Optimize => ("OPTIMIZE", Some("OPTIMIZE")),
    Raise => ("RAISE", Some("RAISE")),
    Top => ("TOP", Some("TOP")),
    Array => ("ARRAY", Some("ARRAY")),
    Distribute => ("DISTRIBUTE", Some("DISTRIBUTE")),
    Option => ("OPTION", Some("OPTION")),
    Eof => ("EOF", None),
    Error => ("ERROR", None),
    Identifier => ("IDENTIFIER", None),
    Hint => ("HINT", None),
    Variant => ("VARIANT", None),
    LiteralInt => ("LITERAL_INT", None),
    LiteralFloat => ("LITERAL_FLOAT", None),
    LiteralHex => ("LITERAL_HEX", None),
    LiteralChars => ("LITERAL_CHARS", None),
    LiteralNchars => ("LITERAL_NCHARS", None),
    LiteralTextBlock => ("LITERAL_TEXT_BLOCK", None),
    Code => ("CODE", None),
    LiteralPath => ("LITERAL_PATH", None),
    LiteralAlias => ("LITERAL_ALIAS", None),
    LineComment => ("LINE_COMMENT", None),
    MultiLineComment => ("MULTI_LINE_COMMENT", None),
    BinaryFloat => ("BINARY_FLOAT", None),
    BinaryDouble => ("BINARY_DOUBLE", None),
    Partition => ("PARTITION", None),
    Partitioned => ("PARTITIONED", None),
    Overwrite => ("OVERWRITE", None),
    Sort => ("SORT", None),
    Lateral => ("LATERAL", None),
    Prewhere => ("PREWHERE", Some("PREWHERE")),
    Settings => ("SETTINGS", Some("SETTINGS")),
    Final => ("FINAL", Some("FINAL")),
    Ttl => ("TTL", Some("TTL")),
    Codec => ("CODEC", Some("CODEC")),
    Sel => ("SEL", Some("SEL")),
    Locking => ("LOCKING", Some("LOCKING")),
    Access => ("ACCESS", Some("ACCESS")),
    Volatile => ("VOLATILE", Some("VOLATILE")),
    Multiset => ("MULTISET", Some("MULTISET")),
    Position => ("POSITION", Some("POSITION")),
    RangeN => ("RANGE_N", Some("RANGE_N")),
    Format => ("FORMAT", Some("FORMAT")),
    Qualify => ("QUALIFY", Some("QUALIFY")),
    Mod => ("MOD", Some("MOD")),
    Contains => ("CONTAINS", Some("CONTAINS")),
    Concat => ("CONCAT", Some("CONCAT")),
    Upsert => ("UPSERT", Some("UPSERT")),
    Add => ("ADD", Some("ADD")),
    Both => ("BOTH", Some("BOTH")),
    Force => ("FORCE", Some("FORCE")),
    Bitmap => ("BITMAP", Some("BITMAP")),
    Ngrambf => ("NGRAMBF", Some("NGRAMBF")),
    Inverted => ("INVERTED", Some("INVERTED")),
    Encode => ("ENCODE", Some("ENCODE")),
    Diststyle => ("DISTSTYLE", Some("DISTSTYLE")),
    Auto => ("AUTO", Some("AUTO")),
    Even => ("EVEN", Some("EVEN")),
    Distkey => ("DISTKEY", Some("DISTKEY")),
    Sortkey => ("SORTKEY", Some("SORTKEY")),
    Compound => ("COMPOUND", Some("COMPOUND")),
    Interleaved => ("INTERLEAVED", Some("INTERLEAVED")),
    Backup => ("BACKUP", Some("BACKUP")),
    Tablet => ("TABLET", Some("TABLET")),
    Repeatable => ("REPEATABLE", Some("REPEATABLE")),
    Tablesample => ("TABLESAMPLE", Some("TABLESAMPLE")),
    Lparen => ("LPAREN", Some("(")),
    Rparen => ("RPAREN", Some(")")),
    Lbrace => ("LBRACE", Some("{")),
    Rbrace => ("RBRACE", Some("}")),
    Lbracket => ("LBRACKET", Some("[")),
    Rbracket => ("RBRACKET", Some("]")),
    Semi => ("SEMI", Some(";")),
    Comma => ("COMMA", Some(",")),
    Dot => ("DOT", Some(".")),
    Dotdot => ("DOTDOT", Some("..")),
    Dotdotdot => ("DOTDOTDOT", Some("...")),
    Eq => ("EQ", Some("=")),
    Gt => ("GT", Some(">")),
    Lt => ("LT", Some("<")),
    LtSubGt => ("LT_SUB_GT", Some("<->")),
    Bang => ("BANG", Some("!")),
    Bangbang => ("BANGBANG", Some("!!")),
    BangTilde => ("BANG_TILDE", Some("!~")),
    BangTildeStar => ("BANG_TILDE_STAR", Some("!~*")),
    Tilde => ("TILDE", Some("~")),
    TildeStar => ("TILDE_STAR", Some("~*")),
    TildeEq => ("TILDE_EQ", Some("~=")),
    Ques => ("QUES", Some("?")),
    Quesques => ("QUESQUES", Some("??")),
    Quesbar => ("QUESBAR", Some("?|")),
    Quesquesbar => ("QUESQUESBAR", Some("??|")),
    Quesamp => ("QUESAMP", Some("?&")),
    Colon => ("COLON", Some(":")),
    Coloncolon => ("COLONCOLON", Some("::")),
    Coloneq => ("COLONEQ", Some(":=")),
    Eqeq => ("EQEQ", Some("==")),
    Eqgt => ("EQGT", Some("=>")),
    Lteq => ("LTEQ", Some("<=")),
    Lteqgt => ("LTEQGT", Some("<=>")),
    Ltgt => ("LTGT", Some("<>")),
    Gteq => ("GTEQ", Some(">=")),
    Bangeq => ("BANGEQ", Some("!=")),
    Banggt => ("BANGGT", Some("!>")),
    Banglt => ("BANGLT", Some("!<")),
    Ampamp => ("AMPAMP", Some("&&")),
    Barbar => ("BARBAR", Some("||")),
    Barbarslash => ("BARBARSLASH", Some("||/")),
    Barslash => ("BARSLASH", Some("|/")),
    Plus => ("PLUS", Some("+")),
    Sub => ("SUB", Some("-")),
    Subgt => ("SUBGT", Some("->")),
    Subgtgt => ("SUBGTGT", Some("->>")),
    Star => ("STAR", Some("*")),
    Slash => ("SLASH", Some("/")),
    Amp => ("AMP", Some("&")),
    Bar => ("BAR", Some("|")),
    Caret => ("CARET", Some("^")),
    Careteq => ("CARETEQ", Some("^=")),
    Percent => ("PERCENT", Some("%")),
    Ltlt => ("LTLT", Some("<<")),
    Ltltlt => ("LTLTLT", Some("<<<")),
    Gtgt => ("GTGT", Some(">>")),
    Gtgtgt => ("GTGTGT", Some(">>>")),
    MonkeysAt => ("MONKEYS_AT", Some("@")),
    MonkeysAtAt => ("MONKEYS_AT_AT", Some("@@")),
    Pound => ("POUND", Some("#")),
    Poundgt => ("POUNDGT", Some("#>")),
    Poundgtgt => ("POUNDGTGT", Some("#>>")),
    MonkeysAtGt => ("MONKEYS_AT_GT", Some("@>")),
    LtMonkeysAt => ("LT_MONKEYS_AT", Some("<@")),
}
