[package]
name         = "druid-wrapper"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description  = "Druid database driver and external-pool wrapper integrations"
repository.workspace = true

[dependencies]
async-trait.workspace = true
bb8.workspace = true
bigdecimal.workspace = true
chrono.workspace = true
deadpool.workspace = true
druid = { path = "../druid" }
futures.workspace = true
rbdc.workspace = true
rbs.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
