//! `PhysicalConnectionLease` 透明委托契约测试。

extern crate druid_core as druid;
use druid::core::{
    ConnectionDefaults, DruidError, ExecResult, PhysicalConnection, PhysicalConnectionCapabilities,
    PhysicalConnectionLease, PhysicalPreparedStatement, Row, Savepoint, SqlTextPreparedStatement,
    SqlWarning, StatementExecuteResult, StatementGeneratedKeys, Value,
};
use std::ops::{Deref, DerefMut};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;

struct ContractConnection {
    closed: bool,
    auto_commit: bool,
    read_only: bool,
    isolation: u8,
    holdability: i32,
    discarded: bool,
    catalog: String,
    schema: String,
}

#[async_trait::async_trait]
impl PhysicalConnection for ContractConnection {
    async fn exec(&mut self, sql: &str, params: Vec<Value>) -> Result<ExecResult, DruidError> {
        assert_eq!(sql, "UPDATE contract");
        assert_eq!(params, vec![Value::Int(7)]);
        Ok(ExecResult {
            rows_affected: 1,
            last_insert_id: Some(9),
            row_count: None,
        })
    }

    async fn execute(
        &mut self,
        sql: &str,
        params: Vec<Value>,
        generated_keys: StatementGeneratedKeys,
    ) -> Result<Vec<StatementExecuteResult>, DruidError> {
        assert_eq!(sql, "EXECUTE contract");
        assert_eq!(params, vec![Value::Int(8)]);
        assert_eq!(generated_keys, StatementGeneratedKeys::AutoGeneratedKeys(1));
        Ok(vec![StatementExecuteResult::Update(ExecResult {
            rows_affected: 3,
            last_insert_id: Some(10),
            row_count: None,
        })])
    }

    async fn fetch(&mut self, sql: &str, params: Vec<Value>) -> Result<Vec<Row>, DruidError> {
        assert_eq!(sql, "SELECT contract");
        assert_eq!(params, vec![Value::String("value".to_string())]);
        Ok(vec![Row::new(vec![Value::Bool(true)])])
    }

    async fn begin(&mut self) -> Result<(), DruidError> {
        self.auto_commit = false;
        Ok(())
    }

    async fn commit(&mut self) -> Result<(), DruidError> {
        self.auto_commit = true;
        Ok(())
    }

    async fn rollback(&mut self) -> Result<(), DruidError> {
        self.auto_commit = true;
        Ok(())
    }

    async fn rollback_to(&mut self, savepoint: &Savepoint) -> Result<(), DruidError> {
        assert_eq!(savepoint.id, 1);
        Ok(())
    }

    async fn set_savepoint(&mut self) -> Result<Savepoint, DruidError> {
        Ok(Savepoint { id: 1, name: None })
    }

    async fn set_savepoint_named(&mut self, name: &str) -> Result<Savepoint, DruidError> {
        Ok(Savepoint {
            id: 2,
            name: Some(name.to_string()),
        })
    }

    async fn release_savepoint(&mut self, savepoint: &Savepoint) -> Result<(), DruidError> {
        assert_eq!(savepoint.name.as_deref(), Some("named"));
        Ok(())
    }

    async fn abort(&mut self) -> Result<(), DruidError> {
        self.closed = true;
        Ok(())
    }

    async fn ping(&mut self) -> Result<(), DruidError> {
        Ok(())
    }

    async fn close(&mut self) -> Result<(), DruidError> {
        self.closed = true;
        Ok(())
    }

    fn is_closed(&self) -> bool {
        self.closed
    }

    fn capabilities(&self) -> PhysicalConnectionCapabilities {
        PhysicalConnectionCapabilities {
            transactions: true,
            savepoints: true,
            auto_commit: true,
            read_only: true,
            transaction_isolation: true,
            holdability: true,
            clear_warnings: true,
            catalog: true,
            schema: true,
        }
    }

    fn auto_commit(&self) -> bool {
        self.auto_commit
    }

    async fn set_auto_commit(&mut self, auto_commit: bool) -> Result<(), DruidError> {
        self.auto_commit = auto_commit;
        Ok(())
    }

    fn read_only(&self) -> bool {
        self.read_only
    }

    async fn set_read_only(&mut self, read_only: bool) -> Result<(), DruidError> {
        self.read_only = read_only;
        Ok(())
    }

    fn transaction_isolation(&self) -> u8 {
        self.isolation
    }

    async fn set_transaction_isolation(&mut self, level: u8) -> Result<(), DruidError> {
        self.isolation = level;
        Ok(())
    }

    fn holdability(&self) -> i32 {
        self.holdability
    }

    async fn set_holdability(&mut self, holdability: i32) -> Result<(), DruidError> {
        self.holdability = holdability;
        Ok(())
    }

    async fn warnings(&mut self) -> Result<Option<SqlWarning>, DruidError> {
        Ok(Some(SqlWarning::new(
            "lease-warning",
            Some("01000".to_string()),
            7,
        )))
    }

    async fn clear_warnings(&mut self) -> Result<(), DruidError> {
        Ok(())
    }

    fn mark_discarded(&mut self) {
        self.discarded = true;
    }

    fn is_discarded(&self) -> bool {
        self.discarded
    }

    fn catalog(&self) -> Option<&str> {
        Some(&self.catalog)
    }

    async fn set_catalog(&mut self, catalog: &str) -> Result<(), DruidError> {
        self.catalog = catalog.to_string();
        Ok(())
    }

    fn schema(&self) -> Option<&str> {
        Some(&self.schema)
    }

    async fn set_schema(&mut self, schema: &str) -> Result<(), DruidError> {
        self.schema = schema.to_string();
        Ok(())
    }

    fn driver_name(&self) -> &str {
        "lease-contract"
    }
}

struct ContractLease {
    connection: Box<dyn PhysicalConnection>,
    drop_count: Arc<AtomicUsize>,
}

impl Deref for ContractLease {
    type Target = Box<dyn PhysicalConnection>;

    fn deref(&self) -> &Self::Target {
        &self.connection
    }
}

impl DerefMut for ContractLease {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.connection
    }
}

impl Drop for ContractLease {
    fn drop(&mut self) {
        self.drop_count.fetch_add(1, Ordering::Relaxed);
    }
}

fn connection_lease(drop_count: Arc<AtomicUsize>) -> PhysicalConnectionLease<ContractLease> {
    PhysicalConnectionLease::new(ContractLease {
        connection: Box::new(ContractConnection {
            closed: false,
            auto_commit: true,
            read_only: false,
            isolation: 2,
            holdability: 0,
            discarded: false,
            catalog: "catalog_a".to_string(),
            schema: "schema_a".to_string(),
        }),
        drop_count,
    })
}

#[tokio::test]
async fn physical_connection_lease_delegates_complete_spi() {
    let drop_count = Arc::new(AtomicUsize::new(0));
    let mut connection = connection_lease(drop_count.clone());

    let exec_result = connection
        .exec("UPDATE contract", vec![Value::Int(7)])
        .await
        .expect("exec must delegate");
    assert_eq!(exec_result.rows_affected, 1);
    let execute_results = connection
        .execute(
            "EXECUTE contract",
            vec![Value::Int(8)],
            StatementGeneratedKeys::AutoGeneratedKeys(1),
        )
        .await
        .expect("generic execute must delegate");
    assert_eq!(execute_results[0].update_count(), 3);
    assert!(!execute_results[0].is_result_set());
    let rows = connection
        .fetch("SELECT contract", vec![Value::String("value".to_string())])
        .await
        .expect("fetch must delegate");
    assert_eq!(rows[0].values, vec![Value::Bool(true)]);
    let result_set = connection
        .fetch_result_set("SELECT contract", vec![Value::String("value".to_string())])
        .await
        .expect("ResultSet fetch must delegate");
    assert!(result_set.next().unwrap());
    assert!(result_set.boolean(1).unwrap());
    let query_prepared: Arc<dyn PhysicalPreparedStatement> =
        Arc::new(SqlTextPreparedStatement::new("SELECT contract"));
    let prepared_result_set = connection
        .fetch_prepared_result_set(
            query_prepared.as_ref(),
            vec![Value::String("value".to_string())],
        )
        .await
        .expect("prepared ResultSet fetch must delegate");
    assert!(prepared_result_set.next().unwrap());
    assert!(prepared_result_set.boolean(1).unwrap());
    let generic_prepared: Arc<dyn PhysicalPreparedStatement> =
        Arc::new(SqlTextPreparedStatement::new("EXECUTE contract"));
    let prepared_results = connection
        .execute_prepared(
            generic_prepared.as_ref(),
            vec![Value::Int(8)],
            StatementGeneratedKeys::AutoGeneratedKeys(1),
        )
        .await
        .expect("prepared generic execute must delegate");
    assert_eq!(prepared_results[0].update_count(), 3);
    let prepared: Arc<dyn PhysicalPreparedStatement> =
        Arc::new(SqlTextPreparedStatement::new("UPDATE contract"));
    assert_eq!(
        connection
            .exec_prepared_batch(prepared.as_ref(), vec![vec![Value::Int(7)]])
            .await
            .expect("prepared batch must delegate"),
        [1]
    );
    connection
        .close_prepared_statement(Arc::clone(&prepared))
        .await
        .expect("prepared close must delegate");
    assert!(prepared.is_closed());

    connection.begin().await.expect("begin must delegate");
    assert!(!connection.auto_commit());
    connection.rollback().await.expect("rollback must delegate");
    connection
        .begin()
        .await
        .expect("second begin must delegate");
    connection.commit().await.expect("commit must delegate");
    connection
        .set_auto_commit(false)
        .await
        .expect("set auto commit must delegate");
    connection
        .set_read_only(true)
        .await
        .expect("set read only must delegate");
    connection
        .set_transaction_isolation(8)
        .await
        .expect("set isolation must delegate");
    connection
        .set_holdability(1)
        .await
        .expect("set holdability must delegate");
    assert_eq!(
        connection
            .warnings()
            .await
            .expect("get warnings must delegate")
            .expect("warning must exist")
            .message(),
        "lease-warning"
    );
    connection
        .clear_warnings()
        .await
        .expect("clear warnings must delegate");
    connection
        .set_catalog("catalog_b")
        .await
        .expect("set catalog must delegate");
    connection
        .set_schema("schema_b")
        .await
        .expect("set schema must delegate");
    assert!(!connection.auto_commit());
    assert!(connection.read_only());
    assert_eq!(connection.transaction_isolation(), 8);
    assert_eq!(connection.holdability(), 1);
    assert_eq!(connection.catalog(), Some("catalog_b"));
    assert_eq!(connection.schema(), Some("schema_b"));

    let anonymous = connection
        .set_savepoint()
        .await
        .expect("anonymous savepoint must delegate");
    connection
        .rollback_to(&anonymous)
        .await
        .expect("rollback to savepoint must delegate");
    let named = connection
        .set_savepoint_named("named")
        .await
        .expect("named savepoint must delegate");
    connection
        .release_savepoint(&named)
        .await
        .expect("release savepoint must delegate");

    connection.ping().await.expect("ping must delegate");
    assert_eq!(connection.driver_name(), "lease-contract");
    assert_eq!(
        connection.capabilities(),
        PhysicalConnectionCapabilities {
            transactions: true,
            savepoints: true,
            auto_commit: true,
            read_only: true,
            transaction_isolation: true,
            holdability: true,
            clear_warnings: true,
            catalog: true,
            schema: true,
        }
    );
    assert!(!connection.is_discarded());
    connection.mark_discarded();
    assert!(connection.is_discarded());
    connection.abort().await.expect("abort must delegate");
    assert!(connection.is_closed());
    connection.close().await.expect("close must delegate");

    drop(connection);
    assert_eq!(drop_count.load(Ordering::Relaxed), 1);
}

#[tokio::test]
async fn connection_defaults_capture_compare_and_reset_complete_state() {
    let drop_count = Arc::new(AtomicUsize::new(0));
    let mut connection = connection_lease(drop_count.clone());
    let defaults = ConnectionDefaults::capture(&connection);

    assert!(defaults.auto_commit());
    assert!(!defaults.read_only());
    assert_eq!(defaults.transaction_isolation(), 2);
    assert_eq!(defaults.holdability(), 0);
    assert!(!defaults.needs_reset(&connection, false));

    connection
        .set_read_only(true)
        .await
        .expect("read only must change");
    connection
        .set_holdability(1)
        .await
        .expect("holdability must change");
    connection
        .set_transaction_isolation(8)
        .await
        .expect("isolation must change");
    connection
        .set_auto_commit(false)
        .await
        .expect("auto commit must change");

    assert!(defaults.needs_reset(&connection, false));
    defaults
        .reset(&mut connection, false)
        .await
        .expect("all supported connection state must reset");
    assert!(!defaults.needs_reset(&connection, false));
    assert!(connection.auto_commit());
    assert!(!connection.read_only());
    assert_eq!(connection.transaction_isolation(), 2);
    assert_eq!(connection.holdability(), 0);

    connection
        .set_transaction_isolation(8)
        .await
        .expect("isolation must change again");
    assert!(!defaults.needs_reset(&connection, true));
    defaults
        .reset(&mut connection, true)
        .await
        .expect("isolation preservation must skip reset");
    assert_eq!(connection.transaction_isolation(), 8);

    drop(connection);
    assert_eq!(drop_count.load(Ordering::Relaxed), 1);
}
