use super::{AgentValue, JdbcAgentClient, JdbcAgentOptions, JdbcAgentPreparedStatement};
use druid::core::{
    DruidError, ExecResult, PhysicalConnection, PhysicalConnectionCapabilities,
    PhysicalPreparedStatement, PreparedStatementKey, Row, StatementExecuteResult,
    StatementGeneratedKeys, Value,
};
use serde_json::{json, Value as JsonValue};
use std::collections::HashMap;
use std::sync::Arc;

/// 由 Druid 独占并通过 JDBC Agent 操作的未池化物理连接。
#[allow(clippy::struct_excessive_bools)]
pub struct JdbcAgentConnection {
    client: JdbcAgentClient,
    auto_commit: bool,
    read_only: bool,
    transaction_isolation: u8,
    closed: bool,
    discarded: bool,
}

impl JdbcAgentConnection {
    /// 启动 Agent，并用显式 JDBC URL、属性和验证 SQL 建立一个物理连接。
    pub async fn connect(
        url: &str,
        validation_query: Option<&str>,
        properties: HashMap<String, String>,
        options: JdbcAgentOptions,
    ) -> Result<Self, DruidError> {
        let client = JdbcAgentClient::connect(
            options,
            json!({
                "url": url,
                "properties": properties,
                "validationQuery": validation_query,
            }),
        )
        .await?;
        Ok(Self {
            client,
            auto_commit: true,
            read_only: false,
            transaction_isolation: 2,
            closed: false,
            discarded: false,
        })
    }

    fn ensure_open(&self) -> Result<(), DruidError> {
        if self.closed || self.discarded || self.client.is_unusable() {
            Err(DruidError::ConnectionDiscarded)
        } else {
            Ok(())
        }
    }

    fn parameters(params: Vec<Value>) -> Result<Vec<AgentValue>, DruidError> {
        params.into_iter().map(AgentValue::from_druid).collect()
    }

    fn rows(payload: &JsonValue) -> Result<Vec<Row>, DruidError> {
        let rows = payload
            .get("rows")
            .cloned()
            .ok_or_else(|| Self::protocol_error("fetch response does not contain rows"))?;
        let rows: Vec<Vec<AgentValue>> = serde_json::from_value(rows)
            .map_err(|error| Self::protocol_error(error.to_string()))?;
        rows.into_iter()
            .map(|values| {
                values
                    .into_iter()
                    .map(AgentValue::into_druid)
                    .collect::<Result<Vec<_>, _>>()
                    .map(Row::new)
            })
            .collect()
    }

    fn exec_result(payload: &JsonValue) -> Result<ExecResult, DruidError> {
        let rows_affected = payload
            .get("rowsAffected")
            .and_then(JsonValue::as_u64)
            .ok_or_else(|| Self::protocol_error("exec response does not contain rowsAffected"))?;
        let last_insert_id = match payload.get("lastInsertId") {
            None | Some(JsonValue::Null) => None,
            Some(value) => Some(
                value
                    .as_i64()
                    .ok_or_else(|| Self::protocol_error("lastInsertId is not a signed integer"))?,
            ),
        };
        Ok(ExecResult {
            rows_affected,
            last_insert_id,
            row_count: None,
        })
    }

    fn generated_keys(generated_keys: StatementGeneratedKeys) -> JsonValue {
        match generated_keys {
            StatementGeneratedKeys::None => json!({"mode": "none"}),
            StatementGeneratedKeys::AutoGeneratedKeys(value) => {
                json!({"mode": "auto", "value": value})
            }
            StatementGeneratedKeys::ColumnIndexes(value) => {
                json!({"mode": "column_indexes", "value": value})
            }
            StatementGeneratedKeys::ColumnNames(value) => {
                json!({"mode": "column_names", "value": value})
            }
        }
    }

    fn statement(
        statement: &dyn PhysicalPreparedStatement,
    ) -> Result<&JdbcAgentPreparedStatement, DruidError> {
        if statement.is_closed() {
            return Err(DruidError::ConnectionDiscarded);
        }
        statement
            .as_any()
            .downcast_ref::<JdbcAgentPreparedStatement>()
            .ok_or_else(|| {
                DruidError::DriverError(
                    "prepared statement was not created by JdbcAgentConnection".to_owned(),
                )
            })
    }

    fn protocol_error(message: impl Into<String>) -> DruidError {
        DruidError::DriverError(format!("invalid JDBC Agent response: {}", message.into()))
    }

    async fn execute_request(
        &mut self,
        sql: &str,
        params: Vec<Value>,
        generated_keys: StatementGeneratedKeys,
    ) -> Result<Vec<StatementExecuteResult>, DruidError> {
        let payload = self
            .client
            .request(
                "execute",
                json!({
                    "sql": sql,
                    "params": Self::parameters(params)?,
                    "generatedKeys": Self::generated_keys(generated_keys),
                }),
            )
            .await?;
        match payload.get("kind").and_then(JsonValue::as_str) {
            Some("result_set") => Ok(vec![StatementExecuteResult::ResultSet(Self::rows(
                &payload,
            )?)]),
            Some("update") => Ok(vec![StatementExecuteResult::Update(Self::exec_result(
                &payload,
            )?)]),
            Some(kind) => Err(Self::protocol_error(format!(
                "unsupported execute result kind '{kind}'"
            ))),
            None => Err(Self::protocol_error(
                "execute response does not contain kind",
            )),
        }
    }
}

impl std::fmt::Debug for JdbcAgentConnection {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("JdbcAgentConnection")
            .field("auto_commit", &self.auto_commit)
            .field("read_only", &self.read_only)
            .field("transaction_isolation", &self.transaction_isolation)
            .field("closed", &self.closed)
            .field("discarded", &self.discarded)
            .finish_non_exhaustive()
    }
}

#[async_trait::async_trait]
impl PhysicalConnection for JdbcAgentConnection {
    async fn exec(&mut self, sql: &str, params: Vec<Value>) -> Result<ExecResult, DruidError> {
        self.ensure_open()?;
        let payload = self
            .client
            .request(
                "exec",
                json!({"sql": sql, "params": Self::parameters(params)?}),
            )
            .await?;
        Self::exec_result(&payload)
    }

    async fn execute(
        &mut self,
        sql: &str,
        params: Vec<Value>,
        generated_keys: StatementGeneratedKeys,
    ) -> Result<Vec<StatementExecuteResult>, DruidError> {
        self.ensure_open()?;
        self.execute_request(sql, params, generated_keys).await
    }

    async fn fetch(&mut self, sql: &str, params: Vec<Value>) -> Result<Vec<Row>, DruidError> {
        self.ensure_open()?;
        let payload = self
            .client
            .request(
                "fetch",
                json!({"sql": sql, "params": Self::parameters(params)?}),
            )
            .await?;
        Self::rows(&payload)
    }

    async fn prepare_physical_statement(
        &mut self,
        key: &PreparedStatementKey,
    ) -> Result<Arc<dyn PhysicalPreparedStatement>, DruidError> {
        self.ensure_open()?;
        Ok(Arc::new(JdbcAgentPreparedStatement::new(key)))
    }

    async fn exec_prepared(
        &mut self,
        statement: &dyn PhysicalPreparedStatement,
        params: Vec<Value>,
    ) -> Result<ExecResult, DruidError> {
        let sql = Self::statement(statement)?.sql().to_owned();
        self.exec(&sql, params).await
    }

    async fn execute_prepared(
        &mut self,
        statement: &dyn PhysicalPreparedStatement,
        params: Vec<Value>,
        generated_keys: StatementGeneratedKeys,
    ) -> Result<Vec<StatementExecuteResult>, DruidError> {
        let sql = Self::statement(statement)?.sql().to_owned();
        self.execute(&sql, params, generated_keys).await
    }

    async fn fetch_prepared(
        &mut self,
        statement: &dyn PhysicalPreparedStatement,
        params: Vec<Value>,
    ) -> Result<Vec<Row>, DruidError> {
        let sql = Self::statement(statement)?.sql().to_owned();
        self.fetch(&sql, params).await
    }

    async fn begin(&mut self) -> Result<(), DruidError> {
        self.ensure_open()?;
        self.client.request("begin", JsonValue::Null).await?;
        self.auto_commit = false;
        Ok(())
    }

    async fn commit(&mut self) -> Result<(), DruidError> {
        self.ensure_open()?;
        self.client.request("commit", JsonValue::Null).await?;
        Ok(())
    }

    async fn rollback(&mut self) -> Result<(), DruidError> {
        self.ensure_open()?;
        self.client.request("rollback", JsonValue::Null).await?;
        Ok(())
    }

    async fn ping(&mut self) -> Result<(), DruidError> {
        self.ensure_open()?;
        self.client.request("ping", JsonValue::Null).await?;
        Ok(())
    }

    async fn close(&mut self) -> Result<(), DruidError> {
        if self.closed {
            return Ok(());
        }
        let result = self.client.close().await;
        self.closed = true;
        result
    }

    fn is_closed(&self) -> bool {
        self.closed || self.client.is_unusable()
    }

    fn capabilities(&self) -> PhysicalConnectionCapabilities {
        PhysicalConnectionCapabilities {
            transactions: true,
            savepoints: false,
            auto_commit: true,
            read_only: true,
            transaction_isolation: true,
            holdability: false,
            clear_warnings: false,
            catalog: false,
            schema: false,
        }
    }

    fn auto_commit(&self) -> bool {
        self.auto_commit
    }

    async fn set_auto_commit(&mut self, auto_commit: bool) -> Result<(), DruidError> {
        self.ensure_open()?;
        self.client
            .request("set_auto_commit", json!({"value": auto_commit}))
            .await?;
        self.auto_commit = auto_commit;
        Ok(())
    }

    fn read_only(&self) -> bool {
        self.read_only
    }

    async fn set_read_only(&mut self, read_only: bool) -> Result<(), DruidError> {
        self.ensure_open()?;
        self.client
            .request("set_read_only", json!({"value": read_only}))
            .await?;
        self.read_only = read_only;
        Ok(())
    }

    fn transaction_isolation(&self) -> u8 {
        self.transaction_isolation
    }

    async fn set_transaction_isolation(&mut self, level: u8) -> Result<(), DruidError> {
        self.ensure_open()?;
        self.client
            .request("set_transaction_isolation", json!({"value": level}))
            .await?;
        self.transaction_isolation = level;
        Ok(())
    }

    fn mark_discarded(&mut self) {
        self.discarded = true;
    }

    fn is_discarded(&self) -> bool {
        self.discarded || self.client.is_unusable()
    }
}
