//! 普通物理 SQL 语句 SPI。
//!
//! 对应 Java 平台对象：`java.sql.Statement`。该对象保存一次普通语句的属性、
//! 批次与关闭生命周期；SQL 的实际执行仍由创建它的 `PhysicalConnection`
//! 完成，避免 Adapter 再持有第二个连接或连接池租约。

use super::{DruidError, ExecResult, Row, SqlWarning};
use std::any::Any;
use std::sync::Mutex;

/// JDBC `Statement` 的结果集创建参数。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhysicalStatementOptions {
    /// 对应 `ResultSet#getType()`。
    pub result_set_type: i32,
    /// 对应 `ResultSet#getConcurrency()`。
    pub result_set_concurrency: i32,
    /// 对应 `ResultSet#getHoldability()`。
    pub result_set_holdability: i32,
}

/// `Statement#execute(...)` 的生成键重载参数。
///
/// 对应 Java：`java.sql.Statement` 的四个 `execute` 重载。枚举保留调用者选择，
/// 使 Adapter 能把原始参数交给驱动，而不是把不同重载折叠成一个布尔开关。
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StatementGeneratedKeys {
    /// `execute(String)`，没有额外生成键参数。
    None,
    /// `execute(String, int)`；保留原始 `autoGeneratedKeys` 值。
    AutoGeneratedKeys(i32),
    /// `execute(String, int[])`；保留列下标顺序和重复项。
    ColumnIndexes(Vec<i32>),
    /// `execute(String, String[])`；保留列名顺序、大小写和重复项。
    ColumnNames(Vec<String>),
}

/// `Statement#execute(...)` 返回的一个 JDBC 结果。
///
/// JDBC 用布尔值区分首结果是否为 ResultSet，并通过 `getMoreResults()` 继续
/// 遍历。Rust SPI 显式保存有序结果，避免通过 SQL 文本猜测查询或更新类型。
#[derive(Debug, Clone, PartialEq)]
pub enum StatementExecuteResult {
    /// 查询结果；`execute` 对该结果返回 `true`。
    ResultSet(Vec<Row>),
    /// 更新结果；`execute` 对该结果返回 `false`。
    Update(ExecResult),
}

impl StatementExecuteResult {
    /// 返回当前结果是否为 JDBC ResultSet。
    pub fn is_result_set(&self) -> bool {
        matches!(self, Self::ResultSet(_))
    }

    /// 返回 JDBC `getUpdateCount()`；ResultSet 返回 `-1`。
    pub fn update_count(&self) -> i64 {
        match self {
            Self::ResultSet(_) => -1,
            Self::Update(result) => i64::try_from(result.rows_affected).unwrap_or(i64::MAX),
        }
    }
}

impl Default for PhysicalStatementOptions {
    fn default() -> Self {
        Self {
            result_set_type: 1003,
            result_set_concurrency: 1007,
            result_set_holdability: 1,
        }
    }
}

/// druid-rust 内部最小普通语句 SPI。
///
/// 对应 Java 平台对象：`java.sql.Statement`。所有可变方法使用内部同步，
/// 使池化包装可共享资源句柄，但不得跨连接租约执行。
pub trait PhysicalStatement: Any + Send + Sync {
    /// 返回具体 Adapter 对象，用于 `Wrapper#unwrap`。
    fn as_any(&self) -> &dyn Any;

    /// 关闭物理语句。
    fn close(&self) -> Result<(), DruidError>;

    /// 返回物理语句是否关闭。
    fn is_closed(&self) -> bool;

    /// 返回创建参数。
    fn options(&self) -> PhysicalStatementOptions;

    /// 返回最大字段字节数。
    fn max_field_size(&self) -> Result<i32, DruidError>;

    /// 设置最大字段字节数。
    fn set_max_field_size(&self, max: i32) -> Result<(), DruidError>;

    /// 返回最大结果行数。
    fn max_rows(&self) -> Result<i32, DruidError>;

    /// 设置最大结果行数。
    fn set_max_rows(&self, max: i32) -> Result<(), DruidError>;

    /// 设置 JDBC escape 处理开关。
    fn set_escape_processing(&self, enabled: bool) -> Result<(), DruidError>;

    /// 返回查询超时秒数。
    fn query_timeout(&self) -> Result<i32, DruidError>;

    /// 设置查询超时秒数。
    fn set_query_timeout(&self, seconds: i32) -> Result<(), DruidError>;

    /// 取消当前执行。
    fn cancel(&self) -> Result<(), DruidError>;

    /// 返回语句警告链。
    ///
    /// 对应 Java：`Statement#getWarnings()`。
    fn warnings(&self) -> Result<Option<SqlWarning>, DruidError> {
        Err(DruidError::UnsupportedOperation {
            operation: "statement_get_warnings",
        })
    }

    /// 清除警告。
    fn clear_warnings(&self) -> Result<(), DruidError>;

    /// 设置游标名称。
    fn set_cursor_name(&self, name: &str) -> Result<(), DruidError>;

    /// 设置抓取方向。
    fn set_fetch_direction(&self, direction: i32) -> Result<(), DruidError>;

    /// 返回抓取方向。
    fn fetch_direction(&self) -> Result<i32, DruidError>;

    /// 设置抓取行数。
    fn set_fetch_size(&self, rows: i32) -> Result<(), DruidError>;

    /// 返回抓取行数。
    fn fetch_size(&self) -> Result<i32, DruidError>;

    /// 添加一条批处理 SQL。
    fn add_batch(&self, sql: &str) -> Result<(), DruidError>;

    /// 清空批处理 SQL。
    fn clear_batch(&self) -> Result<(), DruidError>;

    /// 返回当前批处理快照。
    fn batch(&self) -> Result<Vec<String>, DruidError>;

    /// 访问当前 ResultSet 前执行驱动 getter。
    ///
    /// 对应 Java：`Statement#getResultSet()`。把 getter 保留在物理 SPI，确保
    /// 驱动可在该时点报告错误并进入池化连接 `ExceptionSorter`。
    fn get_result_set(&self) -> Result<(), DruidError> {
        Ok(())
    }

    /// 访问当前更新计数前执行驱动 getter。
    ///
    /// 对应 Java：`Statement#getUpdateCount()`。
    fn get_update_count(&self) -> Result<(), DruidError> {
        Ok(())
    }

    /// 访问生成键 ResultSet 前执行驱动 getter。
    ///
    /// 对应 Java：`Statement#getGeneratedKeys()`。
    fn get_generated_keys(&self) -> Result<(), DruidError> {
        Ok(())
    }

    /// 推进 JDBC 多结果。
    ///
    /// 对应 Java：`Statement#getMoreResults()` 与 `getMoreResults(int)`。默认
    /// 文本 Statement 没有额外驱动状态，但仍精确校验 JDBC current 常量。
    fn get_more_results(&self, current: Option<i32>) -> Result<(), DruidError> {
        if current.is_some_and(|value| !matches!(value, 1..=3)) {
            Err(DruidError::InvalidArgument(
                "current must be CLOSE_CURRENT_RESULT(1), KEEP_CURRENT_RESULT(2), or CLOSE_ALL_RESULTS(3)"
                    .to_string(),
            ))
        } else {
            Ok(())
        }
    }

    /// 设置 poolable。与 Java Druid 一致，仅 `true` 被接受，但对象仍不池化。
    fn set_poolable(&self, poolable: bool) -> Result<(), DruidError>;

    /// Java Druid 的普通 Statement 始终返回 `false`。
    fn is_poolable(&self) -> bool {
        false
    }

    /// 设置完成后自动关闭。
    fn close_on_completion(&self) -> Result<(), DruidError>;

    /// 返回完成后自动关闭状态。
    fn is_close_on_completion(&self) -> Result<bool, DruidError>;
}

#[derive(Debug)]
struct SqlTextStatementState {
    closed: bool,
    max_field_size: i32,
    max_rows: i32,
    escape_processing: bool,
    query_timeout: i32,
    fetch_direction: i32,
    fetch_size: i32,
    cursor_name: Option<String>,
    warnings: Option<SqlWarning>,
    batch: Vec<String>,
    close_on_completion: bool,
}

/// Adapter 通用的普通 SQL 语句资源。
///
/// SQLx、RBDC 与 Toasty 均在连接对象上执行动态 SQL，因此这个实现只保存
/// JDBC Statement 的资源状态，执行仍回到原始 `PhysicalConnection`。
#[derive(Debug)]
pub struct SqlTextStatement {
    options: PhysicalStatementOptions,
    state: Mutex<SqlTextStatementState>,
}

impl SqlTextStatement {
    /// 使用指定结果集参数创建语句。
    pub fn new(options: PhysicalStatementOptions) -> Self {
        Self {
            options,
            state: Mutex::new(SqlTextStatementState {
                closed: false,
                max_field_size: 0,
                max_rows: 0,
                escape_processing: true,
                query_timeout: 0,
                fetch_direction: 1000,
                fetch_size: 0,
                cursor_name: None,
                warnings: None,
                batch: Vec::new(),
                close_on_completion: false,
            }),
        }
    }

    fn with_open<T>(
        &self,
        operation: impl FnOnce(&mut SqlTextStatementState) -> T,
    ) -> Result<T, DruidError> {
        let mut state = self
            .state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        if state.closed {
            return Err(DruidError::Other("statement is closed".to_string()));
        }
        Ok(operation(&mut state))
    }
}

impl PhysicalStatement for SqlTextStatement {
    fn as_any(&self) -> &dyn Any {
        self
    }

    fn close(&self) -> Result<(), DruidError> {
        self.state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .closed = true;
        Ok(())
    }

    fn is_closed(&self) -> bool {
        self.state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .closed
    }

    fn options(&self) -> PhysicalStatementOptions {
        self.options
    }

    fn max_field_size(&self) -> Result<i32, DruidError> {
        self.with_open(|state| state.max_field_size)
    }

    fn set_max_field_size(&self, max: i32) -> Result<(), DruidError> {
        if max < 0 {
            return Err(DruidError::InvalidArgument(
                "max_field_size must not be negative".to_string(),
            ));
        }
        self.with_open(|state| state.max_field_size = max)
    }

    fn max_rows(&self) -> Result<i32, DruidError> {
        self.with_open(|state| state.max_rows)
    }

    fn set_max_rows(&self, max: i32) -> Result<(), DruidError> {
        if max < 0 {
            return Err(DruidError::InvalidArgument(
                "max_rows must not be negative".to_string(),
            ));
        }
        self.with_open(|state| state.max_rows = max)
    }

    fn set_escape_processing(&self, enabled: bool) -> Result<(), DruidError> {
        self.with_open(|state| state.escape_processing = enabled)
    }

    fn query_timeout(&self) -> Result<i32, DruidError> {
        self.with_open(|state| state.query_timeout)
    }

    fn set_query_timeout(&self, seconds: i32) -> Result<(), DruidError> {
        if seconds < 0 {
            return Err(DruidError::InvalidArgument(
                "query_timeout must not be negative".to_string(),
            ));
        }
        self.with_open(|state| state.query_timeout = seconds)
    }

    fn cancel(&self) -> Result<(), DruidError> {
        self.with_open(|_| ())
    }

    fn warnings(&self) -> Result<Option<SqlWarning>, DruidError> {
        self.with_open(|state| state.warnings.clone())
    }

    fn clear_warnings(&self) -> Result<(), DruidError> {
        self.with_open(|state| state.warnings = None)
    }

    fn set_cursor_name(&self, name: &str) -> Result<(), DruidError> {
        self.with_open(|state| state.cursor_name = Some(name.to_string()))
    }

    fn set_fetch_direction(&self, direction: i32) -> Result<(), DruidError> {
        self.with_open(|state| state.fetch_direction = direction)
    }

    fn fetch_direction(&self) -> Result<i32, DruidError> {
        self.with_open(|state| state.fetch_direction)
    }

    fn set_fetch_size(&self, rows: i32) -> Result<(), DruidError> {
        if rows < 0 {
            return Err(DruidError::InvalidArgument(
                "fetch_size must not be negative".to_string(),
            ));
        }
        self.with_open(|state| state.fetch_size = rows)
    }

    fn fetch_size(&self) -> Result<i32, DruidError> {
        self.with_open(|state| state.fetch_size)
    }

    fn add_batch(&self, sql: &str) -> Result<(), DruidError> {
        self.with_open(|state| state.batch.push(sql.to_string()))
    }

    fn clear_batch(&self) -> Result<(), DruidError> {
        self.with_open(|state| state.batch.clear())
    }

    fn batch(&self) -> Result<Vec<String>, DruidError> {
        self.with_open(|state| state.batch.clone())
    }

    fn set_poolable(&self, poolable: bool) -> Result<(), DruidError> {
        if poolable {
            self.with_open(|_| ())
        } else {
            Err(DruidError::UnsupportedOperation {
                operation: "statement_set_poolable_false",
            })
        }
    }

    fn close_on_completion(&self) -> Result<(), DruidError> {
        self.with_open(|state| state.close_on_completion = true)
    }

    fn is_close_on_completion(&self) -> Result<bool, DruidError> {
        self.with_open(|state| state.close_on_completion)
    }
}
